language: go
go:
- 1.10.x
- tip
matrix:
  allow_failures:
  - go: tip
  fast_finish: true
notifications:
  email: false
env:
  global:
  - secure: ShiwFIIagDB7EXlHCMswaly6H7SVZ8HncbA1bWX6siezM2R1vVj/okPBGUY5oWHT3prH7PxDVM9xuCHBwI8axVR06ePJ2EqMttDD64q15/aqniLTJR8yQLfTbLHWLQ0xkx1VMhfWogG7i1l/e4+6qv09xKpDloPZMrn4PjERp6DgtLFws/a9b+YWU0XVYWuhn/kcNcjAznT60S694iaP47h6MRs5tuYIUluuzlSDKxQCYbXBomFz1V+7GIulY0qOkBVEfwfw0cLpSEydHkWOcoYtIrLDKhzJPZPXdBOMYcYOirNrzL5S8Ps09w/f2pfsBjNvHc6An3KBhPndtfCm0tWA3LMU6sn8mP3jUVoSZeACLCENiqYUEg4rw8+69eeVtifGS+A8Zl8HhdOSIdxnveZb6GMZKFiFUr6PUGfVcOJqW32aCn4HX2uPTiifdgARNZtAGUG4CmzGr4HQB1eOa7xNQ6MRlP9JZksSKaTDzr4ac18DtYCxOXc0DgPQec8liOueBENnIOci1NgunJnmD7Jmc0bPTqyZcS/HSeWf8mK2PWf9ew636ekejjvYbTLYcdhzcr26l2enh6+XH/aVgCVXWslAcn/1xVzqxRv8Hr2hyZ9PF9RzjDWsbFN9wpj0f2YnUdAhKHcV1YaKP1AmmbYYVrE0D+skxH7tZgq4ASI=
  - secure: RZH9Pj980wB19lOPpkQBblVhBAPDfdzFAOur08/iKwXsoWIfMV6mx3MucRlGmXtaV0BOV4PddSCLfyBHAuEY57Hg75246iL63nz+I/80JLDZmnV0V2SNF8HTUzJpwLgoG/4eyLe/infHeybapLgtnhWlhA4YpahAWVzIgqxBVG6ijSoGBStK0Yk+i8EnhmPaQj7dhXV352S+oeFusVuA4Y07G//zW0MFW5jtwE5vN/2Hrsx2iPT7jzttQbKSwiiVsdfHTfQS4HQocIgR+XQdwpMJIzKM2lYnPxFFS9rhS2fc1VMkaobMRcjAMUGV74IbUNLX/Jii+r82E1gCEU1lcLyTOgGfZ9sEJLEphUSP7z9Bv3440T77fVzCY6qqL7KGJnBsB0m9HBzMYxwugOYqjPz5Pb3cRAb2if2d7kO8eXgv5y8LsOnUxE7p5VLEmmkzozzuyRgxT6qg189RZGU1YZTcTzl5hMfbLVD1Hwfu6jDjUYVAX4ms44wOD3mjTbQEc2WSN+YorB+fS/8gHtUqf+E7v+/sPZNxC62Zh5zVI8yLBWrmwvURHGySb5qTuJ70Gou4cs9by4AlPsbG0C8wVKWzum1/OYQ22Zt5j8Rjd52KDuGyCB0dMHyRVbbL3QZiH1BSA9Loj+R5yQETbHFVulOvoRBGM+iBEDR0g+lneDk=
before_install:
- go version
- echo $TRAVIS_GO_VERSION
- pip install --user awscli
install:
- make deps
script:
- make test build-lambda
after_success:
- if [[ "$TRAVIS_GO_VERSION" == 1.10.* ]]; then make deploy; fi
